project:
  type: book
  output-dir: _book

execute:
  freeze: auto
  
book:
  title: "A User's Guide to Statistical Inference and Regression"
  author: "Matthew Blackwell"
  output-file: "users-guide"
  reader-mode: true
  public-url: https://mattblackwell.github.io/gov2002-book/
  repo-url: https://github.com/mattblackwell/gov2002-book/
  repo-actions: [edit, issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01_intro.qmd
    - part: "Statistical Inference"
      chapters:
        - design.qmd
        - 02_estimation.qmd
        - 03_asymptotics.qmd
        - 04_hypothesis_tests.qmd
    - part: "Regression"
      chapters:
        - 06_linear_model.qmd
        - 07_least_squares.qmd
        - 08_ols_properties.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: style.css
    include-in-header:
      - file: "macros.jax"
    # include-before-body:
    #   - _dollars.tex
    #   - _bold_html.tex
    #   - _macros.tex
    #   - _dollars.tex
        
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header:
      - _bold.tex
      - _macros_pdf.tex
