project:
  type: book
  output-dir: _book

execute:
  freeze: auto
  
book:
  title: "A User's Guide to Statistical Inference and Regression"
  author: "Matthew Blackwell"
  output-file: "users-guide"
  reader-mode: true
  chapters:
    - index.qmd
    - 01_intro.qmd
    - part: "Stastisitcal Inference"
      chapters:
        - 02_estimation.qmd
        - 03_asymptotics.qmd
        - 04_hypothesis_tests.qmd
    - part: "Regression"
      chapters:
        - 06_linear_model.qmd
        - 07_least_squares.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-before-body:
      - _dollars.tex
      - _bold_html.tex
      - _macros.tex
      - _dollars.tex
        
  pdf:
    documentclass: scrreprt
    include-in-header:
      - _bold.tex
      - _macros_pdf.tex
