project:
  type: book
  output-dir: _book

execute:
  freeze: auto
  
book:
  title: "A User's Guide to Statistical Inference and Regression"
  author: "Matthew Blackwell"
  output-file: "users-guide"
  reader-mode: true
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_estimation.qmd
    - 03_asymptotics.qmd
    - 04_hypothesis_tests.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-before-body:
      - _dollars.tex
      - _macros.tex
      - _dollars.tex
        
  pdf:
    documentclass: scrreprt
    include-in-header:
      - _macros.tex

