project:
  type: book
  output-dir: _book

execute:
  freeze: auto
  
book:
  title: "A User's Guide to Statistical Inference and Regression"
  author:
    - name: Matthew Blackwell
      orcid: 0000-0002-3689-9527
      email: mblackwell@gov.harvard.edu
      url: https://www.mattblackwell.org/
    
  output-file: "users-guide"
  reader-mode: true
  public-url: https://mattblackwell.github.io/gov2002-book/
  repo-url: https://github.com/mattblackwell/gov2002-book/
  repo-actions: [edit, issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Statistical Inference"
      chapters:
        - design.qmd
        - estimation.qmd
        - asymptotics.qmd
        - hypothesis_tests.qmd
    - part: "Regression"
      chapters:
        - linear_model.qmd
        - least_squares.qmd
        - ols_properties.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: style.css
    include-in-header:
      - file: "macros.jax"
    # include-before-body:
    #   - _dollars.tex
    #   - _bold_html.tex
    #   - _macros.tex
    #   - _dollars.tex
        
  pdf:
    documentclass: scrreprt
    keep-tex: true
    fig-pos: th
    fig-width: 10
    fig-height: 6.18
    fig-align: center
    fontfamily: cochineal
    fontsize: 13pt
    include-in-header:
      - _bold.tex
      - _macros_pdf.tex
